import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :nerves_dev_server,
  token_secret: "a very secret string. very secret, indeed.",
  endpoint: [
    # Binding to loopback ipv4 address prevents access from other machines.
    # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
    http: [ip: :any, port: 4000],
    check_origin: false,
    debug_errors: true
    # secret_key_base: "pFPuEB5YsKYlJHYylgc1nDVAg0wvQOnNF6QOw3rOUIIfLdML7zbJ43agwxS337cy"
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :nerves_runtime,
  target: "host",
  modules: %{Nerves.Runtime.KV => Nerves.Runtime.KV.Mock}

config :nerves_runtime,
  kv_backend:
    {Nerves.Runtime.KVBackend.InMemory,
     contents: %{
       "a.nerves_fw_application_part0_devpath" => "/dev/mmcblk0p3",
       "a.nerves_fw_application_part0_fstype" => "f2fs",
       "a.nerves_fw_application_part0_target" => "/root",
       "a.nerves_fw_architecture" => "arm",
       "a.nerves_fw_author" => "Nerves Project Authors",
       "a.nerves_fw_description" => "Unit test config",
       "a.nerves_fw_misc" => "",
       "a.nerves_fw_platform" => "rpi4",
       "a.nerves_fw_product" => "nerves_dev_server",
       "a.nerves_fw_uuid" => "0540f0cd-f95a-5596-d152-221a70c078a9",
       "a.nerves_fw_vcs_identifier" => "",
       "a.nerves_fw_version" => "0.2.17",
       "nerves_fw_active" => "a",
       "nerves_fw_devpath" => "/dev/mmcblk0",
       "nerves_fw_validated" => "1",
       "nerves_serial_number" => "12345"
     }}

config :nerves_motd, runtime_mod: NervesMOTD.MockRuntime
# config :elixir, ansi_enabled: false
